language: ruby
cache: bundler
rvm: 2.2.4
before_install: gem install bundler -v 1.11.2

# This section was added as per https://docs.travis-ci.com/user/code-climate/
# To protect our codeclimate stats rather than adding the Codeclimate API key for ea-area_lookup
# in the open we used this guide https://docs.travis-ci.com/user/encryption-keys/ to encryt the
# value. Essentially install travis gem, then run `travis encrypt <my_code_climate_api_key>`
addons:
  code_climate:
    repo_token:
      secure: "Z/CQJouf45LH6D34mYc0a0mwTk2iHkMRnqMcPWO4Qm5Ov7KQ4e/Echi4lNHSYwODLsnxfTz0ZEhFKXHhPTSWffQ2y4UxE8wko9EeWaTQ/4G+IwRiphfuLZcqwG2Gz/X0PBEBMperVHewrL5lXkd966+wR7Ej/+q95VikM6ePQiKchVt722rxPmdRyEWzRNZaJGIN2RHY/8m9/TPURovUjERMF57LsuaeGBY/9wBBQgWftd6C8iO0QSU7sN+geq67PXQQmVA2Sv/WoQLJ7ZyRDCUTntFv8prKWlDx8s7JAJgkN7/zuCzeI+lbdidEzaQZAyNjPBaIMZSf9q3wefhS0ctlXyIR69JULOJqc/UVWg57cuP3gXXhBiWETTGBKjMyIh8zvqLDApEe6yqtRaq+Vg3Pv5N041e+pyDiNuDnOWUMHb8ObD8HUXqwR9XsXQNGb7c8ut/Ml6+ZwDVLOhR6fGY6ykUD7gFCwOCKw156Ko6XBefDhoWv0oCQ16o4LU/yHXFiPY2mXIvHw1HPzG8cLNvc5jGzJoFDZ7xr4Ck3YUIOwwx2RsgFEUPeSoEbvJuhTn90oa77dQ2CAEe/XF1JNVjW706PHjdvIGy54+htP483ECKw/TnXds6JIK3nUPXM/zLGn5uzHAx1wXAS7RX75ICH9mJjt+kDK3cnwSIodZQ="
deploy:
  provider: rubygems
  api_key:
    secure: "nbNsjHBSar7aWuqUPLuAJ2iNHgJrqn/8fBNL7PYjljjH1hxFzoT+cfT/oNHlFi/Evt9gnEDUuIdsvRsoYHPHwp9r8WUdjMQorNd4KEqElBYTyBOoJ01CLkoxqMae/30c4U9judDsNZNS5UjRpO4r+rCGKFhZatFDxL1Rbpi9MXGYP9M6zMi5NJSFxy6O86Nwn48lXeHJ26keo4NriyxtB/clONepHfPTMY3owSQGs+lZ+5HRVGQgFM7nYwlbaBp9OWco5jrOFpnJFJmftwpBjWQ/miplZLFx+C/vc9Omz4XKeA2aPKBH3N9wdPuzSUMSkL24NuFL3yI4Byg3qCX4Nf/SLgFcoTA/SLtmN1aZhx70iulxOfRB8uFNay9vd3sz8KubBHKg+Pdo59743LkUC+5HgYkvcQJYCLb6J9cY2lSiVbYRFkVefbuZjm/70+qL7sTMZKBSNpBuBjuV4gIRBFUCsdwZFRSjwEyN3wNmLksdNNdUAL76AB1FV1kbbOOLYrs1K7cLbhmYNXn2GUhtBuNK27hNtjmHl90Pr55aN/B4wOQHFsgPhSlN27Fy0op4frhudED14ZJJeIkjnqP0lGstjz0ararXnLhric3R1pg8hEnd2EqIxpQs/lZdBaNBxtgZfpIrBlM04rf+fs92hyFIXpL2YvFF0a+S9ja0mx4="
  on:
    tags: true
    repo: EnvironmentAgency/ea-validation
    all_branches: true
